-- USER INFO
CREATE TABLE IF NOT EXISTS `TB_USER_INFO` (
	`USER_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(50) NOT NULL UNIQUE,
	`USER_NAME` VARCHAR(50) NOT NULL,
	`PASSWORD` VARCHAR(100) NOT NULL,
	`PHONE_NUMBER` VARCHAR(100) NOT NULL,
	`GENDER` VARCHAR(2) NOT NULL,
	`REG_DATE` TIMESTAMP NOT NULL DEFAULT NOW(),
	`ADMIN` BIT DEFAULT 0,
	PRIMARY KEY(`USER_NO`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;
